export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body style={{ backgroundColor: 'blue', padding: 0, margin: 8 }}>
        <div>MAIN LAYOUT</div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
