export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <section style={{ backgroundColor: 'yellow', padding: '10px' }}>
      <div>Dashboard Layout</div>
      {children}
    </section>
  )
}

export default RootLayout
