export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <section className="p-5 bg-yellow-400">
      <div>Dashboard Layout</div>
      {children}
    </section>
  );
};

export default RootLayout;
